### ISSUE TITLE
Adapt plugin to Safari?

### ISSUE THREAD

**Issue by kdeldycke** [leddt/music-link#1]
Found out about this plugin on HN! :)

I'm completely out-of-the-loop regarding browser plugins. But is there any possibility of adapting this one for Safari? 😬

**Comment by leddt** [comment]
Hi! Unfortunately I'm on Windows and I know nothing about Safari plugins. I mostly made this for myself and I only daily drive chrome-based browsers.
If anyone wants to take my code and adapt it to other browsers they are more than welcome to do so!

**Comment by kdeldycke** [comment]
No worries! I know it takes a lot of time to be multi-platforms.
